<a href="home.do">home</a>
<a href="m_insert.do">insert</a>
<a href="m_update.do?num=11">update</a>
<a href="m_delete.do?num=11">delete</a>
<a href="m_selectAll.do">selectAll</a>
<a href="m_selectOne.do?num=11">selectOne</a>
<a href="m_searchList.do?searchKey=name&searchWord=ki">searchList</a>
<a href="m_insertOK.do?id=admin&pw=hi1111&name=lee&tel=031">insertOK</a>
<a href="m_updateOK.do?num=11&id=admin&pw=hi1111&name=lee&tel=031">updateOK</a>
<a href="m_deleteOK.do?num=33">deleteOK</a>