<a href="home.do">home</a>
<a href="b_insert.do">insert</a>
<a href="b_update.do?num=22">update</a>
<a href="b_delete.do?num=22">delete</a>
<a href="b_selectAll.do">selectAll</a>
<a href="b_selectOne.do?num=22">selectOne</a>
<a href="b_searchList.do?searchKey=title&searchWord=sp">searchList</a>
<a href="b_insertOK.do?title=spring&content=hello&writer=admin">insertOK</a>
<a href="b_updateOK.do?num11&title=spring&content=hello&writer=admin">updateOK</a>
<a href="b_deleteOK.do?num22">deleteOK</a>